//articles topics list
export const SELECT_FILTER_TOPIC = 'SELECT_FILTER_TOPIC';
export const POPULATE_TOPICS_LIST = 'POPULATE_TOPICS_LIST';

//image gallery actions
export const SHOW_IMAGE_GALLERY = 'SHOW_IMAGE_GALLERY';
export const HIDE_IMAGE_GALLERY = 'HIDE_IMAGE_GALLERY';

export const POPULATE_IMAGE_GALLERY = 'POPULATE_IMAGE_GALLERY';
export const SHOW_NEXT_IMAGE = 'SHOW_NEXT_IMAGE';

export const GALLERY_IMAGE_LOADED = 'GALLERY_IMAGE_LOADED';

export const ALL_IMAGES_LOADED = 'ALL_IMAGES_LOADED';
export const EMPTY_IMAGE_GALLERY = 'EMPTY_IMAGE_GALLERY';

//fetch requests
export const BEGIN_FETCH_REQUEST = 'BEGIN_FETCH_REQUEST';
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';

//fold images
export const LOAD_FOLD_IMAGES_SUCCESS = 'LOAD_FOLD_IMAGES_SUCCESS';

//projects
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';

//articles
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';

//about
export const LOAD_ABOUT_SUCCESS = 'LOAD_ABOUT_SUCCESS';

//scroll
export const UPDATE_SCROLL = 'UPDATE_SCROLL';