export const SHOW_GALLERY_BREAKPOINT = 1079;
export const SHOW_FOOTER_BREAKPOPINT = 100;
export const SHOW_SIDE_LOGO_BREAKPOINT = 860;
export const HIDE_SIDE_LOGO_BREAKPOINT = 400;
export const CONTRACT_HEADER_BREAKPOINT = 90;
